[build]
  base = "src/frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://web-production-21904.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
