# Nixpacks configuration for Railway
# Force Python environment instead of Node.js

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements_railway.txt"]

[phases.build]
cmds = ["echo 'Python build complete'"]

[start]
cmd = "python comprehensive_demo_server.py"
